<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

?>
<p>
    <?php
    echo nl2br(esc_html(__('As Amazon Partnernet is a data privacy issue and explicitly tracks the visitor this plugin
        will provide a smart way to solve the advertisment on your page using Partnernet.',
        'sumedia-amapn')));
    ?>
</p>