<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

?>
<?php if ($this->link) : ?>
    <div class="sumedia-amapn-link">
        <div class="sumedia-amapn-link-ad">
            <?php echo __('Advertisment', SUMEDIA_AMAPN_PLUGIN_NAME); ?>
        </div>
        <div class="sumedia-amapn-link-amazon-logo">
            <img src="<?php echo SUMEDIA_PLUGIN_URL . SUMEDIA_AMAPN_PLUGIN_NAME . '/assets/images/a-logo-amazon.png'; ?>" alt="<?php echo __('Amazon', SUMEDIA_AMAPN_PLUGIN_NAME); ?>" />
        </div>
        <div class="sumedia-amapn-link-image">
            <a href="<?php echo esc_attr($this->link); ?>" target="_blank">
                <img src="<?php echo esc_attr($this->imageurl); ?>" alt="<?php echo esc_attr(substr($this->title,0, 30)); ?>" />
            </a>
        </div>
        <div class="sumedia-amapn-link-title">
            <a href="<?php echo esc_attr($this->link); ?>" target="_blank">
                <p><?php echo esc_html($this->title); ?></p>
            </a>
        </div>
        <div class="sumedia-amapn-link-price">
            <a href="<?php echo esc_attr($this->link); ?>" target="_blank">
                <p><?php echo esc_html($this->price); ?></p>
            </a>
        </div>
        <div class="sumedia-amapn-link-link">
            <a href="<?php echo esc_attr($this->link); ?>" target="_blank">
                <img src="<?php echo SUMEDIA_PLUGIN_URL . SUMEDIA_AMAPN_PLUGIN_NAME . '/assets/images/cart.gif'; ?>" alt="<?php echo __('Buy', SUMEDIA_AMAPN_PLUGIN_NAME); ?>" />
                <p><?php echo __('Details', SUMEDIA_AMAPN_PLUGIN_NAME); ?></p>
            </a>
        </div>
    </div>
<?php endif; ?>