<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

$shortcode = $this->get('sumedia_amapn_view_shortcode');

?>
<?php if ($shortcode->link) : ?>
    <div class="sumedia-amapn-link">
        <div class="sumedia-amapn-link-ad">
            <?php echo __('Advertisment', 'sumedia-amapn'); ?>
        </div>
        <div class="sumedia-amapn-link-amazon-logo">
            <img src="<?php echo SUMEDIA_PLUGIN_URL . SUMEDIA_AMAPN_PLUGIN_NAME . '/assets/images/a-logo-amazon.png'; ?>" alt="Amazon" />
        </div>
        <div class="sumedia-amapn-link-image">
            <a href="<?php echo esc_attr($shortcode->link); ?>" target="_blank">
                <img src="<?php echo esc_attr($shortcode->imageurl); ?>" alt="<?php echo esc_attr(substr($shortcode->title,0, 30)); ?>" />
            </a>
        </div>
        <div class="sumedia-amapn-link-title">
            <a href="<?php echo esc_attr($shortcode->link); ?>" target="_blank">
                <p><?php echo esc_html($shortcode->title); ?></p>
            </a>
        </div>
        <div class="sumedia-amapn-link-price">
            <a href="<?php echo esc_attr($shortcode->link); ?>" target="_blank">
                <p><?php echo esc_html($shortcode->price); ?></p>
            </a>
        </div>
        <div class="sumedia-amapn-link-link">
            <a href="<?php echo esc_attr($shortcode->link); ?>" target="_blank">
                <img src="<?php echo SUMEDIA_PLUGIN_URL . SUMEDIA_AMAPN_PLUGIN_NAME . '/assets/images/cart.gif'; ?>" alt="<?php echo esc_attr(__('Buy')); ?>" />
                <p><?php echo __('Buy'); ?></p>
            </a>
        </div>
    </div>
<?php endif; ?>